src/cbv_app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cbv_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),    
    re_path('^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),  
    path('create/',views.SchoolCreateView.as_view(),name='create'),  
    re_path('^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),   
    re_path('^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),
    
]

src/fullstack_prj/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

# from first_app import views
# from forms_app import views
# from templates_app import views
# from auth_app import views
from cbv_app import views

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    
    # path('first_app/', include('first_app.urls')),
    # path('formpage/', views.form_name_view, name='form_name'),
    # path('templates_app/', include('templates_app.urls')),
    # path('auth_app/', include('auth_app.urls')),
    # path('logout/', views.user_logout, name='logout'),
    # path('special/', views.special, name='special'),
    path('cbv_app/', include('cbv_app.urls'), name='cbv_app'),
]

src/templates_app/urls.py
from django.urls import path, re_path
from django.conf.urls import include
from . import views

#TEMPLATE TAGGING
app_name = 'templates_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

src/templates_app/models.py
from django.db import models

# Create your models here.

src/templates_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {
        'text': 'hello world',
        'number': 100,
    }
    return render(request, 'templates_app/index.html', context_dict)

def base(request):
    return render(request, 'templates_app/base.html')

def other(request):
    return render(request, 'templates_app/other.html')

def relative(request):
    return render(request, 'templates_app/relative_url_templates.html')

src/templates/templates_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'templates_app:other' %}">Other</a>
                </li>               
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

src/templates/templates_app/index.html
<!DOCTYPE html>
{% extends "templates_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to INDEX!</h1>
        <!-- <h2>This is index.html page showing!</h2> -->
        <h1>{{ text|cut:'world' }}</h1>
        <h2>{{number|add:"99"}}</h2>
    {% endblock %}

src/templates/templates_app/other.html
<!DOCTYPE html>
{% extends "templates_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to OTHER!</h1>
        <h2>This is an example of template inheritance!</h2>
    {% endblock %} 

src/templates/templates_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <h1>Welcome to RELATIVE TEMPLATE!</h1>
    <ul>
        <li><a href="{% url 'templates_app:other' %}">THE OTHER PAGE</a></li>
        <li><a href="{% url 'admin:index' %}">GO TO ADMIN</a></li>
        <li><a href="{% url 'index' %}">HOME</a></li>
    </ul>
</body>
</html>