src/auth_app/urls.py
from django.urls import path, re_path
from django.conf.urls import include
from . import views

#TEMPLATE URLS
app_name = 'auth_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

src/cbv_app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cbv_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),    
    re_path('^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),  
    path('create/',views.SchoolCreateView.as_view(),name='create'),  
    re_path('^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),   
    re_path('^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),
    
]

src/fullstack_prj/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

# from first_app import views
# from forms_app import views
# from templates_app import views
# from auth_app import views
from cbv_app import views

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    
    # path('first_app/', include('first_app.urls')),
    # path('formpage/', views.form_name_view, name='form_name'),
    # path('templates_app/', include('templates_app.urls')),
    # path('auth_app/', include('auth_app.urls')),
    # path('logout/', views.user_logout, name='logout'),
    # path('special/', views.special, name='special'),
    path('cbv_app/', include('cbv_app.urls'), name='cbv_app'),
]

src/auth_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    
    #additional
    portfolio_site = models.URLField(blank=True)
    
    profile_img = models.ImageField(upload_to='profile_imgs', blank=True)

    def __str__(self):
        return self.user.username

src/auth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from auth_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = (
            'username',
            'email',
            'password',
        )

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = (
            'portfolio_site',
            'profile_img',
        )

src/auth_app/views.py
from django.shortcuts import render
from auth_app.forms import UserForm, UserProfileInfoForm

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'auth_app/index.html')



def register(request):

    registered = False
    
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_img' in request.FILES:
                profile.profile_img = request.FILES['profile_img']
            
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request, 'auth_app/registration.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
    })



def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied!")

    else:
            return render(request, 'auth_app/login.html', {})



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

src/templates/auth_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_app:register' %}">Register</a>
                </li>               

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li> 
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth_app:user_login' %}">Login</a>
                    </li>   
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

src/templates/auth_app/index.html
{% extends "auth_app/base.html" %}

{% block body_block %}

    <div class="jumbotron">
        <h1>Django Level Five</h1>
    </div>

{% endblock %}

src/templates/auth_app/login.html
{% extends 'auth_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'auth_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login" class="btn btn-primary">
    </form>
</div>

{% endblock %}

src/templates/auth_app/registration.html
{% extends "auth_app/base.html" %}
{% load staticfiles %}

{% block body_block %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the form:</h3>

            <form action="" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{user_form.as_p}}
                {{ profile_form.as_p}}
                <input type="submit" value="Register" class="btn btn-primary">
            </form>
        {% endif %}
    </div>

{% endblock %}