src/cbv_app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cbv_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),    
    re_path('^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),  
    path('create/',views.SchoolCreateView.as_view(),name='create'),  
    re_path('^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),   
    re_path('^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),
    
]

src/fullstack_prj/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

# from first_app import views
# from forms_app import views
# from templates_app import views
# from auth_app import views
from cbv_app import views

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    
    # path('first_app/', include('first_app.urls')),
    # path('formpage/', views.form_name_view, name='form_name'),
    # path('templates_app/', include('templates_app.urls')),
    # path('auth_app/', include('auth_app.urls')),
    # path('logout/', views.user_logout, name='logout'),
    # path('special/', views.special, name='special'),
    path('cbv_app/', include('cbv_app.urls'), name='cbv_app'),
]

src/cbv_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name        = models.CharField(max_length=256)
    principal   = models.CharField(max_length=256)
    location    = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cbv_app:detail", kwargs={"pk": self.pk})
    

class Student(models.Model):
    name        = models.CharField(max_length=256)
    age         = models.PositiveIntegerField()
    school      = models.ForeignKey(School,related_name='students', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

src/cbv_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    View, 
    TemplateView, 
    ListView, 
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from . import models

# Create your views here.
class IndexView(TemplateView):
    template_name = 'cbv_app/index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'cbv_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location') 
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("cbv_app:list")

src/cbv_app/templates/cbv_app/cbv_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'cbv_app:list' %}">SCHOOLS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">...</a>
                </li>        
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        
        {% endblock %}
    </div>
</body>
</html>

src/cbv_app/templates/cbv_app/school_confirm_delete.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block%}
    <h1>Delete {{school.name}}?</h1>
    <form method="POST"	>
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'cbv_app:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock %}

src/cbv_app/templates/cbv_app/school_detail.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block%}
    <div class="jumbotron">
        <h1>Welcome to the School Detail Page</h1>

        <h3>School details:</h3>
        <p>Name: {{school_detail.name}}</p>
        <p>Principal: {{school_detail.principal}}</p>
        <p>Location: {{school_detail.location}}</p>

        <h3>Students:</h3>
        {% for student in school_detail.students.all %}
            <p>{{student.name}} who is {{student.age}} years old.</p>
        {% endfor %}
    </div>

    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'cbv_app:update' pk=school_detail.pk %}">Update</a></p>
    </div>
{% endblock %}

src/cbv_app/templates/cbv_app/school_form.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block%}
    <h1>
        {% if not from.instance.pk %}
            Create school
        {% else %}
            Update School
        {% endif %}
    </h1>

    <form method="POST"	>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock %}

src/cbv_app/templates/cbv_app/school_list.html
{% extends "cbv_app/cbv_app_base.html" %}

{% block body_block%}
    <h1>Welcome to a list of all the schools!</h1>
    <ol>
        {%  for school in schools %}
            <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
        {% endfor %}
    </ol>
{% endblock %}